FROM python:3-alpine
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools 
RUN pip3 install flask flask_restful pymysql
COPY test1_API /app/test1_AP
WORKDIR /app/test1_AP
CMD ["/usr/local/bin/python3", "./run_test.py"]
