version: '3'

services:
  api-server:
    container_name: api-server
    image: alpine-python:v1
    ports:
      - "8881:8881"
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=api_test
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql-data:/var/lib/mysql:rw"
