FROM python:3-alpine
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools flask flask_restful pymysql
RUN python --version && pip list
COPY test1_API /app/test1_AP
